#公共配置
server:
  #tomcat 编码格式
  port: 9331
  tomcat:
    uri-encoding: UTF-8
  uri-encoding: UTF-8
spring:
  #网络请求配置
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  #连接池配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/project?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true
    username: root
    password: root
    druid:
      validationQuery: SELECT 1
      initialSize: 10
      minIdle: 10
      maxActive: 200
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
  cloud:
    config:
      discovery:
        service-id: config
        enabled: true
      uri: http://192.168.9.105/9231
      name: base
      profile: dev
      username: yangy
      password: yangy
    application:
      name: manage
  application:
    name: order
redis:
  host: 127.0.0.1
  port: 6379
  timeout: 1000
  password:

#mybatisPlus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号隔离
  typeAliasesPackage: com.yangy.**.entity
  refresh: true
#  global-config:
#    db-config:
#      db-type: MYSQL
#      column-like: false
#      id-type: id_worker
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#  global-config:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 0
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    field-strategy: 2
#    #驼峰下划线转换
#    db-column-underline: true
#    #刷新mapper 调试神器
#    refresh-mapper: true
#    #数据库大写下划线转换
#    #capital-mode: true
#    #序列接口实现类配置
#    #key-generator: com.baomidou.springboot.xxx
#    #逻辑删除配置
#    #    logic-delete-value: 1
#    #    logic-not-delete-value: 0
#    #自定义填充策略接口实现
#    #自定义SQL注入器
#    #sql-injector: com.baomidou.springboot.xxx
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false

test:
  msg: 这是一条测试消息5
#公共配置
registration:
  master:
    hostname: localhost
    port: 9230
eureka:
  client:
    service-url:
      defaultZone: http://${registration.master.hostname}:${registration.master.port}/eureka/

feign:
  hystrix:
    enabled: true





